name: Nix Flake Eval Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "scripts/**"
      - "**.md"
      - "**.nu"
      - "Justfile"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "scripts/**"
      - "**.md"
      - "**.nu"
      - "Justfile"

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes

      - name: Check NixOS Configuration Builds
        run: |
          echo 'Checking NixOS configuration builds'
          echo 'Building dock01 (manager node)...'
          nix build .#nixosConfigurations.dock01.config.system.build.toplevel --show-trace --print-build-logs
          echo 'Building dock03 (worker node without GPU)...'
          nix build .#nixosConfigurations.dock03.config.system.build.toplevel --show-trace --print-build-logs
          echo 'Building storage01 (storage node)...'
          nix build .#nixosConfigurations.storage01.config.system.build.toplevel --show-trace --print-build-logs
          echo 'All configuration builds completed successfully!'
